### PR TITLE
Add transaction details

### PR DESCRIPTION
**Pull request by reez**
### Description

Enhances [transactions](https://docs.rs/bdk/1.0.0-alpha.2/bdk/wallet/struct.Wallet.html#method.transactions) method on Wallet.

### Notes to the reviewers

Previously #432 had a simplified return type to list `Transaction`s. This PR enhances `transactions` to return additional types. 

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [ ] I've added tests for the new feature
* [ ] I've added docs for the new feature

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [ ] I'm linking the issue being fixed by this PR

## Summary by CodeRabbit

- **New Features**
	- Enhanced transaction details display across platforms (Android, JVM, Python, Swift) with the addition of `CanonicalTx` and `ChainPosition`.
- **Refactor**
	- Updated transaction retrieval methods to ensure consistency in how transaction information is accessed and displayed.

### CODE REVIEW

**Comment by reez** [comment]
> Love it! It's a neat way to pull what we need out of that complex data type.
> 
> I just need to look into understanding the lifetime parameters more before giving the final review, but should be able to do this later today.

Great! Our conversation last week spurred me on to this, so thanks for that. And thanks for the heads up on reviewing it.

**Comment by thunderbiscuit** [comment]
Good stuff. I cleared up my issue with the lifetimes, and as per the call earlier added a commit that renames those structures to the Rust based ones, as well as moved them to the types.rs file.

**Comment by reez** [comment]
> Good stuff. I cleared up my issue with the lifetimes, and as per the call earlier added a commit that renames those structures to the Rust based ones, as well as moved them to the types.rs file.

Ok. Sorry I didn't mean for you to have to make a commit, just a comment on the PR with the requested changes and I could make the commit with the changes. But since you have the commit pushed up for it are you going to rename `pub confirmation: ChainPosition,` to `pub chain_position: ChainPosition,`?

**Review by thunderbiscuit — APPROVED** [review]
ACK f698d463927e8533931f5720f0e0aa1aa5c962b4.

**Comment by reez** [comment]
> Oh shoot I misunderstood you on the call. And thanks for the review! I just pushed the fix now.

LGTM!

**Pull request merged**
