### PR TITLE
chore(swift): update build-local-swift.sh to use xcodebuild tool

### PR DESCRIPTION
**Pull request by notmandatory**
### Description

I updated the build script to use the xcodebuild tool which creates the xc.framework so we don't need to manually copy header and `libbdkffi.a` files or manually create the `Info.plist` file.

I don't know if this will fix any current problems, but it's a start to getting things built the Apple™	way.

### Notes to the reviewers

For this update I referenced:

* https://www.strathweb.com/2023/07/calling-rust-code-from-swift/#switching-to-a-framework
* https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle#Generate-the-XCFramework-bundle

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
Really good to see the build workflow being updated and cleaned up a bit. A few thoughts just so I don't forget:
- The bdk.xcframework directory can now be completely removed from version control I think
- Since the PR in bitcoindevkit/bdk-swift#49 now uses the script, I think a name change for that script might work well

**Comment by reez** [comment]
> * We just need to make sure that this new Info.plist doesn't impact our fix for XCode 15.3

Just did some testing a few different ways to see if it would break in Xcode 15.3+ and Xcode 16 beta, and everything worked as expected, so that's really great, nice Steve!

**Comment by thunderbiscuit** [comment]
Note that this fixes #552.

**Comment by thunderbiscuit** [comment]
I have also built this locally and all tests pass. CI looks good. @reez do I understand that you have tried using this in XCode and the example iOS app?

It's an important change because it rewrites how we build and publish our Swift package, but I don't know that we could test it any more than what we did (let me know if you'd like to still test it in different ways). My take on this is that I'd rather merge it before we get to the beta releases and the true 1.0, so we catch anything and fix if needed earlier than later.

It's an important change so I'll wait for ACKs of all 3 of us before merging.

**Review by thunderbiscuit — APPROVED** [review]
Tested ACK 21ac5267b537e6883f12a7fafb4f44eae7d5a4a4.

**Comment by reez** [comment]
> I have also built this locally and all tests pass. CI looks good. @reez do I understand that you have tried using this in XCode and the example iOS app?
> 
> It's an important change because it rewrites how we build and publish our Swift package, but I don't know that we could test it any more than what we did (let me know if you'd like to still test it in different ways). My take on this is that I'd rather merge it before we get to the beta releases and the true 1.0, so we catch anything and fix if needed earlier than later.
> 
> It's an important change so I'll wait for ACKs of all 3 of us before merging.


>  @reez do I understand that you have tried using this in XCode and the example iOS app?
That's correct. 

> I don't know that we could test it any more than what we did
I'm not sure how we could either.

>  My take on this is that I'd rather merge it before we get to the beta releases and the true 1.0
Agree.

Tested ACK 21ac5267b537e6883f12a7fafb4f44eae7d5a4a4.

**Review by reez — APPROVED** [review]

**Pull request merged**
