### PR TITLE
Update bdk dependency to 0.22

### PR DESCRIPTION
**Pull request by thunderbiscuit**
The bindings do not build when attempting this upgrade because `get_balance()` now returns a `Balance` struct (this was merged in bitcoindevkit/bdk#640)

```sh
error[E0308]: mismatched types
   --> src/lib.rs:433:9
    |
432 |     fn get_balance(&self) -> Result<u64, Error> {
    |                              ------------------ expected `Result<u64, bdk::Error>` because of return type
433 |         self.get_wallet().get_balance()
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u64`, found struct `Balance`
    |
    = note: expected enum `Result<u64, _>`
               found enum `Result<Balance, _>`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `bdk-ffi` due to previous error
```

When we upgrade to `0.22.0` we could decide to add the `Balance` struct to the bindings, or simply return the total by calling `get_total()`, which returns a `u64` (same as we have now).

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
Because `Balance` is very simple (4 u64 fields) I decided to take a stab at bringing it in the FFI layer and test it in my test suite.

As is, the `Balance` struct works well, but the methods on it are not ported to the FFI layer. I'm not sure how to enable them without rewriting the struct in the FFI... @notmandatory any ideas?

**Comment by thunderbiscuit** [comment]
ACK [5d1d7ba](https://github.com/bitcoindevkit/bdk-ffi/pull/193/commits/5d1d7ba4f1a0c9f26c87db43df3979bac0407d2f). Ready for merging when the new BDK version comes out.

**Comment by notmandatory** [comment]
I rebased and updated the CHANGELOG.

**Comment by notmandatory** [comment]
Updated PR branch with final bdk release version 0.22.  This should be ready to merge.

**Review by notmandatory — APPROVED** [review]
ACK 3c6075ad96afa238dc3ceca71ba82cb10088bb90

**Pull request merged**
