### PR TITLE
iOS Example App Improvements

### PR DESCRIPTION
**Pull request by konjoinfinity**
TABConf 2021 Hackathon submission to improve upon iOS example app for the bitcoin development kit (bdk-ffi).   

Improvements include:

- UI Similar to Android App
- Added wallet mneumonic and wallet recovery screens
- Added QR display for receive view (generates QR code from internal wallet address)
- Added QR scanning functionality which populates the to: input field

@futurepaul was responsible for rebuilding Thunderbiscuit's Android UI in SwiftUI.
@konjoinfinity was responsible for QR code scanning and display, and integration / compilation of the project

### CODE REVIEW

**Comment by artfuldev** [comment]
Nice work, thank you so much for your efforts! Will review these and get back to you shortly. cc @notmandatory

**Comment by artfuldev** [comment]
Hi, apologies for the delay. Once again, thank you for the great work!

At a high level, there's just a few things that when addressed would make it easier to get this merged:
1. Do we need `shcqrcode.png`? If not, can we remove that (ideally from the git history itself, as it seems to contain sensitive information)
2. The `examples/ios` folder is meant to be a simple container. I see we've added packages directly to that. Can we change that package to be added to the sample app itself? We might have other sample apps in the future and it would be good to isolate changes to this example in its own scope instead of at the container level.  We can also remove the README. What do you think?
3. The example app was just meant to be a showcase of how to use SDKs so I'd prefer just leaving the initial styles as they are. if it's not too much work, can the styling be reverted back to the original? The idea is that the app simply showcases API usage instead of trying to show how to build a cool app with a cool UX thereby showing more complicated stuff than is required to quickly start using the swift bindings. Do you agree?

Thanks again for your work - can't wait to get these changes merged.

I will review the changes once I hear back from you.

**Comment by notmandatory** [comment]
Please rebase on master to pickup changes from #83

**Comment by konjoinfinity** [comment]
> Hi, apologies for the delay. Once again, thank you for the great work!
> 
> At a high level, there's just a few things that when addressed would make it easier to get this merged:
> 
> 1. Do we need `shcqrcode.png`? If not, can we remove that (ideally from the git history itself, as it seems to contain sensitive information)
> 2. The `examples/ios` folder is meant to be a simple container. I see we've added packages directly to that. Can we change that package to be added to the sample app itself? We might have other sample apps in the future and it would be good to isolate changes to this example in its own scope instead of at the container level.  We can also remove the README. What do you think?
> 3. The example app was just meant to be a showcase of how to use SDKs so I'd prefer just leaving the initial styles as they are. if it's not too much work, can the styling be reverted back to the original? The idea is that the app simply showcases API usage instead of trying to show how to build a cool app with a cool UX thereby showing more complicated stuff than is required to quickly start using the swift bindings. Do you agree?
> 
> Thanks again for your work - can't wait to get these changes merged.
> 
> I will review the changes once I hear back from you.


1) shcqrcode.png contains no sensitive data, the info embedded is for testing purposes.  A sample QR code I used from another project.  It has been removed.

2) I understand what you are asking for but I don't know how to accomplish this and don't have the time to figure out how to.  Removed the readme.

3) We wanted to match the styles as closely as we could to the Android bdk presented at TabConf.

**Comment by thunderbiscuit** [comment]
I think this might be a case where the demo app is better off outside of the library repository. The point about wanting to keep the code in this library very lean and devoid of polish is good IMO, and I'd even go as far as saying I don't really know if _any_ demo apps belong in the library directly. Better still is to keep a list of a few links in the readme with great sample examples and implementations, and leave the little demo needed to the test suite in the library.

@konjoinfinity the job you guys did for TABConf is really awesome, but it's maybe out of scope for the library itself to host and maintain it, just like it doesn't maintain the Android one I presented at the workshop. Could we maybe just link to it in the readme?

**Comment by artfuldev** [comment]
@thunderbiscuit That's a great idea to add links to the readme and they get to keep the commit history as well!

@konjoinfinity what do you think? If you'd like to contribute to this repo, you can change this PR into one updating the readme with a link to the sample!

As an alternative, I can just merge this PR and do the changes I requested on to of them - but then you might lose the exact version of the app demo the you've built here. Let me know @konjoinfinity

**Comment by futurepaul** [comment]
Hey sorry to be out of the convo here I've been super busy since we built this.

@artfuldev I think I agree with your concerns about the styling and additional dependencies this introduces. I got caught up in the fun of styling the app and kind of forgot how that would mess with the purpose of this example app.

Probably best to close this PR and we can create a new repo that simply holds this example, similar to @thunderbiscuit's https://github.com/thunderbiscuit/bitcoindevkit-android-sample-app repo. then add that to the readme like you suggested

@konjoinfinity I can build that repo if you'd like, since I know you didn't want to sign up for maintaining this in perpetuity.

**Comment by konjoinfinity** [comment]
> Hey sorry to be out of the convo here I've been super busy since we built this.
> 
> @artfuldev I think I agree with your concerns about the styling and additional dependencies this introduces. I got caught up in the fun of styling the app and kind of forgot how that would mess with the purpose of this example app.
> 
> Probably best to close this PR and we can create a new repo that simply holds this example, similar to @thunderbiscuit's https://github.com/thunderbiscuit/bitcoindevkit-android-sample-app repo. then add that to the readme like you suggested
> 
> @konjoinfinity I can build that repo if you'd like, since I know you didn't want to sign up for maintaining this in perpetuity.

@futurepaul I'm good with that.

**Comment by notmandatory** [comment]
Thanks guys, will close the one.  And when you create a new repo let me know and I should soon™️ have a new properly packaged and versioned `bdk-swift` swift package you can use as your dependency.

**Pull request closed without merging**
