### PR TITLE
Refactor Rust code

### PR DESCRIPTION
**Pull request by thunderbiscuit**
This PR is quite extensive in scope, but is only a refactoring of the layout of our Rust code for the bindings.

### Notes to the reviewers
I have some questions regarding the visibility modifiers. I tried to make everything `pub(crate)`, but not quite sure if that's the right call.

Also snuck in another small change: bump the development versions of bdk-android, bdk-jvm, and bdk-python.

### Changelog notice
No changelog notice

#### All Submissions:
* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

### CODE REVIEW

**Comment by notmandatory** [comment]
Looks good so far, this will make it easier to navigate the code and reduce PR merge conflicts.

**Comment by notmandatory** [comment]
Did you mean to add the file: `api-docs/python/docs/__pycache__/bdk.cpython-310.pyc` ?

**Comment by thunderbiscuit** [comment]
Shoot no I didn't! Removed.

**Review by notmandatory — APPROVED** [review]
ACK 302ad8dea80ee9cc1ce57568083efd7cfdda8749

Looks good! I didn't go line by line, but confirmed the right bits of code are in the right files.

**Pull request merged**
