### PR TITLE
Add FeeRate struct and PSBT fee_amount and fee_rate functions

### PR DESCRIPTION
**Pull request by notmandatory**
### Description

Add FeeRate struct and fee_amount() and fee_rate() functions on PartiallySignedTransaction.

### Notes to the reviewers

This PR is dependent on https://github.com/bitcoindevkit/bdk/pull/782.

### Changelog notice

- Breaking Changes
  - Renamed PartiallySignedBitcoinTransaction to PartiallySignedTransaction to be consistent with `rust-bitcoin`
- APIs Added
  - Add FeeRate struct
  - Add fee_amount() and fee_rate() functions on PartiallySignedTransaction

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [x] I've added tests for the new feature
* [x] I've added docs for the new feature

### CODE REVIEW

**Comment by notmandatory** [comment]
Rebased, will need to rebase and update again once bdk 0.24 is released and then will be done.

**Comment by notmandatory** [comment]
Once #221 is merged this PR will need to be rebased and then it will be ready to merge. But I don't expect any code changes so it's ready to review now.

**Review by thunderbiscuit — APPROVED** [review]
ACK [4a12e77](https://github.com/bitcoindevkit/bdk-ffi/pull/208/commits/4a12e77e746ef25a7451b6c88d0bbf99a78d922d).

**Comment by notmandatory** [comment]
Rebased to pickup #221

**Comment by thunderbiscuit** [comment]
Re-ACK [ae1ea99](https://github.com/bitcoindevkit/bdk-ffi/pull/208/commits/ae1ea99ed3f26f33ead92d4a91588ae32d9e110b).

**Review by thunderbiscuit — APPROVED** [review]

**Pull request merged**
