### PR TITLE
Add MVP Python API docs

### PR DESCRIPTION
**Pull request by thunderbiscuit**
Not ready, but the core machinery is there. I just don't really know how to make them look really "Pythonesque" yet.

bdkpython docs

### CODE REVIEW

**Comment by wilfredallyn** [comment]
The screenshot reminds me of the docs for `requests`, a popular http python library.

It has [examples](https://requests.readthedocs.io/en/latest/api/#requests.get) of pythonic documentation

The docs source code is [here](https://github.com/psf/requests/tree/main/docs).

Another example of python docs is the [pandas library](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html).

The pandas docs source code is [here]([Here|https://github.com/pandas-dev/pandas/tree/main/doc/source])

Also, I have a co-worker who just automated the python docs for our work repos. If there is a specific questions you have, let me know, and I can ask for help.

**Comment by thunderbiscuit** [comment]
After further discussions around this, I'm not sure we want to take up the work of maintaining this in the current state. The Koltin API docs have proven the approach to work but also to be burdensome to maintain, and we currently don't have anyone interested in picking up this work directly for Python. Moreover, our plan over the next 6 months is to move uniffi-rs to the latest [proc-macro system](https://github.com/bitcoindevkit/bdk-ffi/issues/300), which might offer the ability to write proper inline documentation for the bindings.

@notmandatory let me know if you agree but for the moment I am considering closing this PR. I think the foundational work is there so if ever we wanted to pick it up we could, but I don't want to give the impression that this is being worked on directly at the moment.

**Comment by notmandatory** [comment]
I agree it's better to not spend the time on this right now. Our long term solution is to get bdk-ffi updated to the uniffi-rs macros.. and then get uniffi-rs improved to generate language binding docs for us. 🤞

**Comment by thunderbiscuit** [comment]
Thanks for looking into it @wilfredallyn! Will close for now.

**Pull request closed without merging**
