### PR TITLE
Add simple kotlin, swift and python integration tests

### PR DESCRIPTION
**Pull request by notmandatory**
### Description

Add simple kotlin, swift and python integration tests. These tests confirm fixes in #216 and #214.

### Notes to the reviewers

To skip integration tests use: 

`cargo test --lib`.

Otherwise java, kotlin, swift, and python need to be installed, and you must run tests with: 

`CLASSPATH=./tests/jna/jna-5.8.0.jar cargo test`

### Changelog notice

- Integration tests added, see tests/README.md for updated instructions for running tests. #215

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [x] I've added tests for the new feature
* [x] I've added docs for the new feature

#### Bugfixes:

* [x] I've added tests to reproduce the issue which are now passing

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
@waterst0ne from your log in the link I think you're calling the tests with a classpath that has a typo: you're using 
```sh
CLASSPATH=./test/jna/...
```
instead of 
```sh
CLASSPATH=./tests/jna/
```

Let me know if that fixes it.

**Comment by thunderbiscuit** [comment]
The Kotlin and Python tests work for me, and I assume the Swift ones would as well but I'm running into a Rosetta/M1 issue. Here is my error:

```sh
ld: warning: ignoring file /Users/user0/repos/bdk-ffi/target/debug/libbdkffi.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
```

**Review by thunderbiscuit — APPROVED** [review]

**Comment by notmandatory** [comment]
Yes those swift warnings are expected and unfortunately no way to disable certo warnings in swift. Also I get the same swift error with the M1 macOS .. but works with x86 macOS or Linux (which is what CI is using).

**Comment by waterst0ne** [comment]
> Yes those swift warnings are expected and unfortunately no way to disable certain warnings in swift. Also I get the same swift error with the M1 macOS .. but works with x86 macOS or Linux (which is what CI is using).

Ack #ee6ee8139afd74c858216ed99ffdec92dc101787 

> Yeah I think those are simply the Swift compiler warnings to help clarify that the backticks are not required. But uniffi-rs puts them there for all languages I think, so that you don't have any surprises.
> 
> ACK [ee6ee81](https://github.com/bitcoindevkit/bdk-ffi/pull/215/commits/ee6ee8139afd74c858216ed99ffdec92dc101787).



> Yes those swift warnings are expected and unfortunately no way to disable certain warnings in swift. Also I get the same swift error with the M1 macOS .. but works with x86 macOS or Linux (which is what CI is using).


ACK [ee6ee81](https://github.com/bitcoindevkit/bdk-ffi/pull/215/commits/ee6ee8139afd74c858216ed99ffdec92dc101787).

**Pull request merged**
