### PR TITLE
Add compact block filters blockchain feature using the Nakamoto client

### LINKED ISSUE #118: Add compact block filters blockchain support

### PR DESCRIPTION
**Pull request by thunderbiscuit**
Work in Progress.

Fixes #118.

### Description
This PR adds the compact block filters blockchain option.

### Notes to the reviewers
Not ready for merge yet. Lots to be tested still.

Questions I still want to answer:
- [ ] How much size does it add to the final binary we ship for Android/iOS?
- [ ] Full testing on testnet/mainnet

### Changelog notice
```txt
## Added Features
    - Compact Block Filters client ([Nakamoto]) [#207]

[Nakamoto](https://github.com/cloudhead/nakamoto)
[#207](https://github.com/bitcoindevkit/bdk-ffi/pull/207)
```

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:
* [ ] I've added tests for the new feature
* [ ] I've added docs for the new feature

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
I decided to try it on my desktop using bdk-jvm and a small Kotlin cli wallet I made a while back. It seems to be syncing _something_ so far, so that's good. But as a side note the `progress` float returned seem to be going up and down. Sometimes in the 60s sometimes in the 40s, back and forth.

float

**Comment by thunderbiscuit** [comment]
Oh darn it worked! Took about 3-4 minutes and the wallet is displaying the correct balance for the descriptor. 🔥 🔥 🔥

**Comment by thunderbiscuit** [comment]
Ok so so far here is what is happening:

1. On desktop and using bdk-jvm the new blockchain appears to be working
2. On Android not at all, throwing this error: `Cbf(Nakamoto(Handle(Disconnected)))` (both in the emulator and on a physical device, same error)

The odd thing is that these two libraries are pretty much duplicates of each other. So the issue is definitely coming from something on Android.

@cloudhead @rajarshimaitra any ideas? I tried looking through the Nakamoto codebase but couldn't quite pick out the `Handle(Disconnected)` error and what could be triggering it.

**Comment by rajarshimaitra** [comment]
Thanks @thunderbiscuit .. Thats super progress.. Although I am as clueless about the `HandleDisconnect` error.. Just making some wild guess.. The sync process starts by spawning a separate thread that runs the nakamoto client process in background.. The `HandleDisconnect` could mean that for some reason that thread is dropped or terminated and the main bdk thread cannot communicate with it anymore..

Is that something that happens on android? Does it require special consideration for spawning threads?

**Comment by cloudhead** [comment]
> Thanks @thunderbiscuit .. Thats super progress.. Although I am as clueless about the `HandleDisconnect` error.. Just making some wild guess.. The sync process starts by spawning a separate thread that runs the nakamoto client process in background.. The `HandleDisconnect` could mean that for some reason that thread is dropped or terminated and the main bdk thread cannot communicate with it anymore..
> 
> Is that something that happens on android? Does it require special consideration for spawning threads?

This is likely what's going on.

**Comment by thunderbiscuit** [comment]
Ok good stuff guys, thanks for chiming in. I'll need to dig a bit more into this. It means that somehow the connection between the native binary and the glue code is handled differently on Android than it is server-side, and I don't know that we have encountered that before. My next step will be to make sure it works in the unit tests (which run on the dev machine and not in the emulator/device).

Side note, I tested with the Python library and it worked right off the bat.

**Comment by thunderbiscuit** [comment]
Folks it looks like we have liftoff!

<center>
    Nakamoto
</center>

The issue was that I had given a default value of `./nakamoto` for the `datadir` field of the `CBFConfig` in the ffi layer, and in my tests on desktop/server/mobile I left that field `null` so it was using the default path. This worked on the server because I called my test wallet from a directory where I had write permission. 

On Android however, the process is not started from a place where you have write permission (and I haven't quite figured out _where_ this default path leads to the attempted directory creation but it doesn't really matter for now), and so that default path simply doesn't create the `.nakamoto` directory (I'd be nice to get a specific error for that maybe). Subsequent sync calls would then fail. The trick was to provide a valid path for the app to write the directory in. On Android this looks like 

```kotlin
val path: String = applicationContext.filesDir.toString()
val nakamotoConfig = CbfConfig(
    Network.TESTNET,
    "$path/bdk-nakamoto",
)
```

I suspect the easiest way to deal with this in the short run is to make the `datadir` field required on the FFI layer (as per my latest commit), but there might be other ways as well.

A few notes for myself/future reference:
1. On the server a full sync of testnet was about 300-400 MB for the 3 files (`filters.db`, `headers.db`, `peers.json`)
2. The process times out on the UI thread (no surprise there), but that means we end up launching it in a coroutine, and that's where we can get into tricky situations (#205)

**Comment by cloudhead** [comment]
Great work!

In terms of catching the error, is there something nakamoto could have done better? I suspect there would have been an error logged, though I recently reworked all the logging because there were some issues in 0.3.0.

On your notes:
* Mainnet should take about 100 MB total disk space, since there are about 3x less blocks compared to testnet.
* Since <https://github.com/cloudhead/nakamoto/pull/105/commits/1c5afc977fdeb6ab4dd869ec339870b18b03c174>, the block header/filter loading is interruptible, though I'm still working on the API
* I'm curious about the binary size, since the `nakamoto-node` which contains everything that would be imported into bdk is only 5.7MB on my system (release mode).

**Comment by andreasgriffin** [comment]
I tried to get CBF working in python, and was successfull on mainnet (not regtest unfortunately) ( see [diff](https://github.com/bitcoindevkit/bdk-ffi/compare/master...andreasgriffin:bdk-ffi:compact_filters2)  on my branch https://github.com/andreasgriffin/bdk-ffi/commits/compact_filters2   )

image

**Comment by andreasgriffin** [comment]
I really like CBF because it has good privacy, while also offering great speed.

@thunderbiscuit : Does it makes sense to develop https://github.com/andreasgriffin/bdk-ffi/commits/compact_filters2  into a PR right now, even though bdk has a major restructuring ahead?

**Comment by thunderbiscuit** [comment]
Hey thanks for taking a look! 

Instead of making a new PR on this repo directly, I think it might make sense to keep this PR up to date (it's quite old at this point) so that it's easier to review and keep up to date in the future. Would you mind making your PR on my fork instead? Your contributions will still be shown because your commits will actually show up on this PR once I merge your PR on my branch.

I'll rebase this (it's about 500 commits behind) and everything will break, but would you be interested in opening a PR on my [cbf branch](https://github.com/thunderbiscuit/bdk-ffi/tree/cbf) with your working implementation?

To be transparent with you I will not actually consider merging this in the FFI layer until the 1.0 release of BDK, which will impact significantly how sync is done (and so you can expect sizeable changes to the compact block filter crate as well). But for anyone who would like to experiment with it and for testing the advances made by the Rust BDK team on CBF it would be great to have this PR fairly up-to-date and ready to play with.

**Comment by thunderbiscuit** [comment]
Ok I've rebased the changes. If you PR on my CBF branch I'll take the time to review and merge there, so we can get this PR in working order!

**Comment by thunderbiscuit** [comment]
I'm closing this in favour or #379.

**Pull request closed without merging**
